export const codeBlocks = {
	javascript: [
		`function add(a, b) {^~return a + b;^}`,
		`function multiply(a, b) {^~return a * b;^}`,
		`function subtract(a, b) {^~return a - b;^}`,
		`function divide(a, b) {^~return a / b;^}`,
		`function square(n) {^~return n * n;^}`,
		`function isEven(n) {^~return n % 2 === 0;^}`,
		`function isPositive(n) {^~return n > 0;^}`,
		`function greet(name) {^~console.log("Hello, " + name + "!");^}`,
		`function isPalindrome(s) {^~const rev = s.split("").reverse().join("");^~return s === rev;^}`,
		`function factorial(n) {^~if (n <= 1) return 1;^~return n * factorial(n - 1);^}`,
		`const max = (a, b) => (a > b ? a : b);`,
		`const sum = (arr) => arr.reduce((a, b) => a + b, 0);`,
		`function capitalize(str) {^~return str.charAt(0).toUpperCase() + str.slice(1);^}`,
		`function clamp(v, lo, hi) {^~return Math.min(Math.max(v, lo), hi);^}`,
		`const unique = (arr) => [...new Set(arr)];`,
		`function sleep(ms) {^~return new Promise((r) => setTimeout(r, ms));^}`,
		`function flatten(arr) {^~return arr.flat(Infinity);^}`,
		`function repeat(str, n) {^~return str.repeat(n);^}`,
		`function zip(a, b) {^~return a.map((v, i) => [v, b[i]]);^}`,
		`function range(start, end) {^~return Array.from({ length: end - start }, (_, i) => i + start);^}`,
	],

	python: [
		`def add(a, b):^~return a + b`,
		`def multiply(a, b):^~return a * b`,
		`def is_even(n):^~return n % 2 == 0`,
		`def greet(name):^~print("Hello, " + name + "!")`,
		`def square(n):^~return n * n`,
		`def is_positive(n):^~return n > 0`,
		`def factorial(n):^~if n <= 1:^~~return 1^~return n * factorial(n - 1)`,
		`def is_palindrome(s):^~return s == s[::-1]`,
		`def clamp(v, lo, hi):^~return max(lo, min(v, hi))`,
		`def gcd(a, b):^~return a if b == 0 else gcd(b, a % b)`,
		`def flatten(lst):^~return [x for sub in lst for x in sub]`,
		`def unique(lst):^~return list(set(lst))`,
		`def capitalize(s):^~return s[0].upper() + s[1:]`,
		`def is_prime(n):^~if n < 2:^~~return False^~for i in range(2, int(n**0.5) + 1):^~~if n % i == 0:^~~~return False^~return True`,
		`def average(lst):^~return sum(lst) / len(lst)`,
		`def zip_lists(a, b):^~return list(zip(a, b))`,
		`def chunk(lst, n):^~return [lst[i:i+n] for i in range(0, len(lst), n)]`,
		`def count_char(s, c):^~return s.count(c)`,
		`def reverse(lst):^~return lst[::-1]`,
		`def power(base, exp):^~return base ** exp`,
	],

	c: [
		`int add(int a, int b) {^~return a + b;^}`,
		`int subtract(int a, int b) {^~return a - b;^}`,
		`int multiply(int a, int b) {^~return a * b;^}`,
		`int max(int a, int b) {^~return a > b ? a : b;^}`,
		`int min(int a, int b) {^~return a < b ? a : b;^}`,
		`int square(int n) {^~return n * n;^}`,
		`int is_even(int n) {^~return n % 2 == 0;^}`,
		`int abs_val(int n) {^~return n < 0 ? -n : n;^}`,
		`int gcd(int a, int b) {^~return b == 0 ? a : gcd(b, a % b);^}`,
		`int factorial(int n) {^~if (n <= 1) return 1;^~return n * factorial(n - 1);^}`,
		`void swap(int *a, int *b) {^~int t = *a;^~*a = *b;^~*b = t;^}`,
		`int clamp(int v, int lo, int hi) {^~if (v < lo) return lo;^~if (v > hi) return hi;^~return v;^}`,
		`int str_len(const char *s) {^~int len = 0;^~while (*s++) len++;^~return len;^}`,
		`int power(int b, int e) {^~int r = 1;^~for (int i = 0; i < e; i++) r *= b;^~return r;^}`,
		`int sum_array(int arr[], int n) {^~int t = 0;^~for (int i = 0; i < n; i++) t += arr[i];^~return t;^}`,
		`int is_prime(int n) {^~if (n < 2) return 0;^~for (int i = 2; i * i <= n; i++)^~~if (n % i == 0) return 0;^~return 1;^}`,
		`double average(int arr[], int n) {^~int s = 0;^~for (int i = 0; i < n; i++) s += arr[i];^~return (double)s / n;^}`,
		`int count_char(const char *s, char c) {^~int n = 0;^~while (*s) if (*s++ == c) n++;^~return n;^}`,
		`int lcm(int a, int b) {^~return a / gcd(a, b) * b;^}`,
		`void fill(int arr[], int n, int v) {^~for (int i = 0; i < n; i++) arr[i] = v;^}`,
	],

	cpp: [
		`int add(int a, int b) {^~return a + b;^}`,
		`bool is_even(int n) {^~return n % 2 == 0;^}`,
		`int max(int a, int b) {^~return a > b ? a : b;^}`,
		`int factorial(int n) {^~if (n <= 1) return 1;^~return n * factorial(n - 1);^}`,
		`void swap(int &a, int &b) {^~int t = a;^~a = b;^~b = t;^}`,
		`int gcd(int a, int b) {^~return b == 0 ? a : gcd(b, a % b);^}`,
		`int sum(const vector<int> &v) {^~int t = 0;^~for (int x : v) t += x;^~return t;^}`,
		`bool is_prime(int n) {^~if (n < 2) return false;^~for (int i = 2; i * i <= n; i++)^~~if (n % i == 0) return false;^~return true;^}`,
		`int clamp(int v, int lo, int hi) {^~return max(lo, min(v, hi));^}`,
		`double average(const vector<int> &v) {^~int s = 0;^~for (int x : v) s += x;^~return (double)s / v.size();^}`,
		`bool is_palindrome(const string &s) {^~int lo = 0, hi = s.size() - 1;^~while (lo < hi)^~~if (s[lo++] != s[hi--]) return false;^~return true;^}`,
		`void print(const vector<int> &v) {^~for (int x : v) cout << x << " ";^~cout << "\n";^}`,
		`vector<int> range(int start, int end) {^~vector<int> v;^~for (int i = start; i < end; i++) v.push_back(i);^~return v;^}`,
		`int power(int base, int exp) {^~int r = 1;^~while (exp-- > 0) r *= base;^~return r;^}`,
		`string repeat(const string &s, int n) {^~string r;^~for (int i = 0; i < n; i++) r += s;^~return r;^}`,
		`bool has_duplicate(vector<int> v) {^~set<int> seen;^~for (int x : v)^~~if (!seen.insert(x).second) return true;^~return false;^}`,
		`void reverse(vector<int> &v) {^~int lo = 0, hi = v.size() - 1;^~while (lo < hi) swap(v[lo++], v[hi--]);^}`,
		`int binary_search(vector<int> &v, int t) {^~int lo = 0, hi = v.size() - 1;^~while (lo <= hi) {^~~int mid = lo + (hi - lo) / 2;^~~if (v[mid] == t) return mid;^~~if (v[mid] < t) lo = mid + 1;^~~else hi = mid - 1;^~}^~return -1;^}`,
		`map<char, int> freq(const string &s) {^~map<char, int> m;^~for (char c : s) m[c]++;^~return m;^}`,
		`int count_if(const vector<int> &v, function<bool(int)> f) {^~int n = 0;^~for (int x : v) if (f(x)) n++;^~return n;^}`,
	],

	csharp: [
		`int Add(int a, int b) {^~return a + b;^}`,
		`bool IsEven(int n) {^~return n % 2 == 0;^}`,
		`int Max(int a, int b) {^~return a > b ? a : b;^}`,
		`string Greet(string name) {^~return "Hello, " + name + "!";^}`,
		`int Square(int n) {^~return n * n;^}`,
		`int Factorial(int n) {^~if (n <= 1) return 1;^~return n * Factorial(n - 1);^}`,
		`int Clamp(int v, int lo, int hi) {^~return Math.Max(lo, Math.Min(v, hi));^}`,
		`int Sum(int[] arr) {^~int total = 0;^~foreach (int x in arr) total += x;^~return total;^}`,
		`double Average(int[] arr) {^~return arr.Average();^}`,
		`bool IsPrime(int n) {^~if (n < 2) return false;^~for (int i = 2; i * i <= n; i++)^~~if (n % i == 0) return false;^~return true;^}`,
		`string Capitalize(string s) {^~if (string.IsNullOrEmpty(s)) return s;^~return char.ToUpper(s[0]) + s.Substring(1);^}`,
		`bool IsPalindrome(string s) {^~char[] arr = s.ToCharArray();^~Array.Reverse(arr);^~return s == new string(arr);^}`,
		`int GCD(int a, int b) {^~return b == 0 ? a : GCD(b, a % b);^}`,
		`int Power(int b, int e) {^~return (int)Math.Pow(b, e);^}`,
		`string Repeat(string s, int n) {^~return string.Concat(Enumerable.Repeat(s, n));^}`,
		`int[] Reverse(int[] arr) {^~return arr.Reverse().ToArray();^}`,
		`List<int> Range(int start, int end) {^~return Enumerable.Range(start, end - start).ToList();^}`,
		`bool HasDuplicate(int[] arr) {^~return arr.Length != arr.Distinct().Count();^}`,
		`int CountIf(int[] arr, Func<int, bool> pred) {^~return arr.Count(pred);^}`,
		`void PrintArray<T>(T[] arr) {^~Console.WriteLine(string.Join(", ", arr));^}`,
	],
};
